#pragma config(Motor,  port1,           LeftMotor1,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftMotor2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RightMotor1,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RightMotor2,   tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
This program is made to test the base of the robot.
The base has 4 motors and the function of this program
is to move the robot forward, backword, and turn based on
remote control input. The two thumbsticks will control
the speed and direction of the robot. When both the thubsticks
are pushed up, the robot will move forward. When both the
thumbsticks are pushed down, the robot will move backwords.
When one thubstick is pushed up and another is pushed down,
the robot will turn.
*/

task main()
{

while(true) //Continuously loops so driver control is always running
{

motor[LeftMotor1]	= vexRT[Ch2];		//the motors equal the input speeds determined by the thumbsticks
motor[LeftMotor2]= vexRT[Ch2];		//vexRT[Chx] function returns an integer based thumbstick value
motor[RightMotor1]	= vexRT[Ch4];
motor[RightMotor2]= vexRT[Ch4];

}

}
