#pragma config(Sensor, dgtl1,  armQuad,        sensorQuadEncoder)
#pragma config(Motor,  port1,           LeftMotor1,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftMotor2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RightMotor1,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RightMotor2,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Arm2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Arm3,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           Arm4,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
This set of code is made for the remote control. Based on the inputs
of the remote, the motors on the robot will respond as follows\
This program also uses a quad encoder which is a sensor that returns
the number of degrees based on axle ticks. The quad encoder is used
to rotate the arm until it reaches a certain point and back down.
*/

task main()
{

wait1Msec(2000);				//2 seconds delay
SensorValue[armQuad]=0;	//initializes the quad encoder to zero

while(true)
{

if(vexRT[Btn5U]==1&&SensorValue[armQuad]<398) 	//When button 5D on the controller is pressed, the robot arm moves up, arm cannot move 398 quad encoder value
{
	motor[Arm1]=128;
	motor[Arm2]=128;
	motor[Arm3]=-128;
	motor[Arm4]=-128;
}
else if(vexRT[Btn5D]==1&&SensorValue[armQuad]>0)	//else if the button 5U is pressed, the robot arm moves down, arm cannot moved below quad value 0 or initial state
{
	motor[Arm1]=-128;
	motor[Arm2]=-128;
	motor[Arm3]=128;
	motor[Arm4]=128;
}
else	//if neither of the buttons are pressed, the robot arm does not move
{
	motor[Arm1]=0;
	motor[Arm2]=0;
	motor[Arm3]=0;
	motor[Arm4]=0;
}

if(vexRT[Btn7U]==1)	//if button 7U is pressed, the robot claw opens
{
motor[Claw]=68;
}
else if(vexRT[Btn7D]==1) //else if button 7D is pressed, the robot claw closes
{
motor[Claw]=-68;
}
else					//if neither those two buttons are pressed, the claw motor is zero
{
motor[Claw]=0;
}

int leftSpeed	= vexRT[Ch2];
int rightSpeed = vexRT[Ch4];

if(leftSpeed<15)	//if the joystick is slightly and an angle then the speed of left side of base is zero
{
motor[LeftMotor1]=0;
motor[LeftMotor2]=0;
}
else					//if the joystick is at more of an angle than 15, the speed of the base is equal to the joystick value
{
motor[LeftMotor1]=leftSpeed;
motor[LeftMotor2]=leftSpeed;
}

if(rightSpeed<15)		//same applies to the right motors of the base as the left motors of the base
{
motor[RightMotor1]=0;
motor[RightMotor2]=0;
}
else
{
motor[RightMotor1]=rightSpeed;
motor[RightMotor2]=rightSpeed;
}

}

}
